config/routes.rb
Rails.application.routes.draw do
  root :to => 'web/main#index'

  scope module: :web do
    controller :traps do
      match '/:trap_id' => :capture, via: :all
    end

    controller :requests do
      get '/:trap_id/requests' => :index, as: 'requests'
      get '/:trap_id/requests/:id' => :show, as: 'request'
    end
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :trap

  validates :trap, presence: true

  after_create :publish

  serialize :headers,      JsonParser
  serialize :query_params, JsonParser
  serialize :cookies,      JsonParser

  private

  def publish
    PublishService.new(self).perform
  end
end

app/models/trap.rb
class Trap < ActiveRecord::Base
  has_many :requests, dependent: :destroy, inverse_of: :trap
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/web/base_controller.rb
class Web::BaseController < ApplicationController
  layout 'web'

  rescue_from ActiveRecord::RecordNotFound do |exception|
    render file: "public/404.html", status: 404
  end
end

app/controllers/web/main_controller.rb
class Web::MainController < Web::BaseController
  def index

  end
end

app/controllers/web/requests_controller.rb
class Web::RequestsController < Web::BaseController
  before_action :load_trap, only: [:index, :show]

  def index
    @requests = @trap.requests.order(created_at: 'desc').page(params[:page])
  end

  def show
    @request = @trap.requests.find(params[:id])
  end

  private

  def load_trap
    @trap = Trap.find(params[:trap_id])
  end
end

app/controllers/web/traps_controller.rb
class Web::TrapsController < Web::BaseController
  skip_before_action :verify_authenticity_token, only: [:capture]

  def capture
    service = RequestCaptureService.new(request)

    if service.perform
      render nothing: true, status: 200
    else
      render nothing: true, status: 400
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_hash_format(hash)
    string = ""

    hash.each_pair do |key, value|
      string << sanitize("#{key}: #{ value }", tags: [], attributes: [])
      string << "</br>"
    end

    string.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RequestsTrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/web.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Requests Trap</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/web/main/index.html.erb
<% readme = <<-README
REQUESTS-TRAP The rules
- this app must be written in Rails 
- commit early and often 
- track the time spent developing the project 
- as a guideline, this is a small project and should not take much time to complete 
- the app must be deployed to Heroku. 
- email the instructions for accessing the app on Heroku to roma@milushov.ru 
- when done, give read-only access to your repo to the user @milushov on Github 
- in that email, include the time spent on the project any anything else you want to share.

Requests Trap: A tool for capture and display HTTP requests.
This simple tool is useful during the development of apps that integrate with external services, such as http clients, webhooks, etc.
The Requests Trap app ('Req App') provides these services with an endpoint to which they can send requests and notifications.
For example, let's assume we are developing an ecommerce site named "Shop" with PayPal integration.
During development, Shop can use Req App to see PayPal requests via a specific endpoint.

If a Req App user gives this URL to the PayPal service:
  http://requests-trap.com/shop
Then the user could see the IPN notifications sent by PayPal here:
  http://requests-trap.com/shop/requests
The user can choose any url, all the requests made to that url can be viewed by anyone that knows the url, so he can use hard-to-guess urls to avoid that:
  http://requests-trap.com/mysupersecreturlxj34

How it works 
The app has four routes:
  / # splash page with some instructions 
  /:trap_id # send requests to be captured here
  /:trap_id/requests # display requests here 
  /:trap_id/requests/:id # display a single request here
￼
Any request [POST, PUT, GET, DELETE, ...] made to /:trap_id will be saved in the db and displayed in /:trap_id/requests
In response to any request made to /:trap_id, we will respond with the correct http code if success or not.
In /:trap_id/requests we should see the trap_id in the header, and a list of the received requests, ordered by creation date DESC.
Each request item should display all the information contained in the request, well formatted:
- request date 
- remote ip 
- request-method
- scheme
 - query-string 
- query-params 
- cookies 
- headers 
- ...

Also include a copy of the raw response, hidden by default, opened by clicking a link.
New requests should appear on the page in real time, without a page refresh. 
README
%>
<%= simple_format readme %>

app/views/web/requests/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to @trap.id, requests_path(@trap.id), class: 'navbar-brand' %>
    </div>
  </div>
</nav>

app/views/web/requests/_modal.html.erb
<a href="#" data-toggle="modal" data-target="#<%= id %>">
  display
</a>

<div class="modal fade" id="<%= id %>" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= title %></h4>
      </div>
      <div class="modal-body">
        <% case body %>
        <% when String %>
          <%= simple_format body %>
        <% when Hash %>
          <%= simple_hash_format body %>
        <% else %>
          <%= body %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/web/requests/_request_template.html.erb
<script id="request-template" type="text/template">
  <tr>
    <td>{{ request.created_at }}</td>
    <td>{{ request.remote_ip }}</td>
    <td>{{ request.request_method }}</td>
    <td>{{ request.scheme }}</td>
    <td>{{ request.query_string }}</td>
    <td>{{{ request.query_params }}}</td>

    <td>
      <a href="#" data-toggle="modal" data-target="#modal-cookies-{{ request.id }}">
        display
      </a>

      <div class="modal fade" id="modal-cookies-{{ request.id }}" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
              <h4 class="modal-title" id="myModalLabel">Cookies</h4>
            </div>
            <div class="modal-body">
              {{{ request.cookies }}}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </td>

    <td>
      <a href="#" data-toggle="modal" data-target="#modal-headers-{{ request.id }}">
        display
      </a>

      <div class="modal fade" id="modal-headers-{{ request.id }}" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
              <h4 class="modal-title" id="myModalLabel">Headers</h4>
            </div>
            <div class="modal-body">
                {{{ request.headers }}}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </td>

    <td>
      <a href="#" data-toggle="modal" data-target="#modal-raw-{{ request.id }}">
        display
      </a>

      <div class="modal fade" id="modal-raw-{{ request.id }}" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
              <h4 class="modal-title" id="myModalLabel">Raw</h4>
            </div>
            <div class="modal-body">
              {{{ request.raw }}}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </td>

    <td>
      <a class="btn btn-primary" href="/{{ request.trap.id }}/requests/{{ request.id }}">show</a>
    </td>
  </tr>
</script>

app/views/web/requests/index.html.erb
<script type="text/javascript">
  $(function() {
    subscribe(
      "<%= $pubnub.env[:publish_key] %>",
      "<%= $pubnub.env[:subscribe_key] %>",
      "<%= PublishService.channel_name_for_trap(@trap) %>"
    );
  });
</script>

<%= render 'header' %>
<%= render 'request_template' %>

<h3>Requests</h1>
<table class="table table-striped requests">
  <tr class="headers">
    <th>created_at</th>
    <th>remote_ip</th>
    <th>request_method</th>
    <th>scheme</th>
    <th>query_string</th>
    <th>query_params</th>
    <th>cookies</th>
    <th>headers</th>
    <th>raw</th>
    <th>#</th>
  </tr>
  <% @requests.each do |request|%>
    <tr>
      <td><%= request.created_at.strftime("%T %D") %></td>
      <td><%= request.remote_ip %></td>
      <td><%= request.request_method %></td>
      <td><%= request.scheme %></td>
      <td><%= request.query_string %></td>
      <td><%= simple_hash_format(request.query_params) %></td>
      <td>
        <%- modal_id = "modal-cookies-#{ request.id }" %>
        <%= render 'modal', id: modal_id, body: request.cookies, title: 'Cookies' %>
      </td>
      <td>
        <%- modal_id = "modal-headers-#{ request.id }" %>
        <%= render 'modal', id: modal_id, body: request.headers, title: 'Headers' %>
      </td>
      <td>
        <%- modal_id = "modal-raw-#{ request.id }" %>
        <%= render 'modal', id: modal_id, body: request.raw, title: 'Raw' %>
      </td>
      <td><%= link_to "show", request_path(@trap.id, request), class: 'btn btn-primary' %></td>
    </tr>
  <% end %>
</table>

<%= paginate @requests %>

app/views/web/requests/show.html.erb
<%= render 'header' %>

<h3>Request</h1>

<dl>
  <dt>created_at</dt>
  <dd><%= @request.created_at %></dd>
  <dt>remote_ip</dt>
  <dd><%= @request.remote_ip %></dd>
  <dt>@request_method</dt>
  <dd><%= @request.request_method %></dd>
  <dt>scheme</dt>
  <dd><%= @request.scheme %></dd>
  <dt>query_string</dt>
  <dd><%= @request.query_string %></dd>
  <dt>query_params</dt>
  <dd><%= simple_hash_format(@request.query_params) %></dd>
  <dt>cookies</dt>
  <dd><%= simple_hash_format(@request.cookies) %></dd>
  <dt>headers</dt>
  <dd><%= simple_hash_format(@request.headers) %></dd>
  <dt>raw</dt>
  <dd><%= simple_format @request.raw %></dd>
</dl>